<p>This is <b>about me broski</b>. </p>
<p>Hi my name is Claudia, but many friends call me CJ! I am a twenty-one year old laaaaaaady, a taurus, and am unfortunately not very tall.</p>
<p>Despite being from oh so tiny Dallas, Georgia -- I&apos;tm quite familar with the city scape because I&apos;tm roughly 15 minutes from Marietta and less an hour&apos;ts drive to Atlanta.
After graduating this May, I hope to move to Atlanta.</p>
<p>Unliked Jenna, back in Dallas I only have three dogs. A Great Pyranese named Wren, a Great Pyr-Aussie Sheppard Mix named Bridgette, and an obese beagled named Bo.
I love my dogs with all of my heart, so here are some dorky pics of them!</p>

<img src="https://photos.app.goo.gl/AfpSuLrwknZxHnyYA" alt=" [Here's a pic of Wren being a goob] ">
<p>Fun Fact: My family runs an instagram for our dogs @boandfriends__ </p>