<p>Welcome to Jenna&apos;s Ratchet Salon!</p>
<p>Jenna&apos;s Services include the following: </p>
<ul>
<li>Hair braiding</li>
<li>Acrylic Nails</li>
<li>Acrylic Nails to individuals by the name of Julien Solomita</li>
<li>Acrylic Toe Nails</li>
<li>Eyebrow bleaching</li>
<li>Eyebrow shaving</li>
</ul>

<img src="https://media.tenor.com/images/34eff992cd77d63018ea6dbe7e51221f/tenor.gif" alt=" [video: https://www.youtube.com/watch?v=AZngynzkNQ0 ] ">

<p> To book Jenna, Subscribe to her YouTube channel: <a href="urhttps://www.youtube.com/channel/UC9gFih9rw0zNCK3ZtoKQQyAl">YEET</a></p>