<p>Welcome home <b>beech</b>. </p>

<p>Welcome to Jenna&apos;s Ratchet Salon! Services include the following: </p>

<ul>
<li>Hair braiding</li>
<li>Acrylic Nails</li>
<li>Acrylic Nails to individuals by the name of Julien Solomita</li>
<li>Acrylic Toe Nails</li>
<li>Eyebrow bleaching</li>
<li>Eyebrow shaving</li>
</ul>

<img src="https://media.tenor.com/images/34eff992cd77d63018ea6dbe7e51221f/tenor.gif" alt=" [video: https://www.youtube.com/watch?v=AZngynzkNQ0 ] ">