


<p><center>This about <b>Jenna Marbles beeech</b>.</p>

<img src ="jenna-w-beard.jpg" height="50%" width="50%" alt=" [This is supposed to be a pic of Jenna with an sfx beard on]">

<p>Jenna marbles is a *tall* thirty-two year old laaaaaady who posts videos on youtube every Wednesday slash Thursday. Some habits that Jenna has is playing with her cerments - Cerm, Peache, and honorarily Marbles.
Recently, Jenna and her partner Julien have adopted a rescue Italian Grey Hound, whom they have named Bunny. </p> </center>